### ISSUE TITLE
Show hidden files and directories in file manager

### ISSUE THREAD

**Issue by sumanthratna** [tjcsl/director4#23]
# Feature Request
either show hidden files in the leftbar file viewer or add an option in the right click menu that toggles whether these files are displayed

# Motivation
If I need to edit `.git/config`, for example, I _have_ to use the git CLI even though I prefer using nvim. It would be nice if I could open this file in the ACE editor, just as I can view any other file. 

# Implementation
If you all decide to go with displaying hidden files by default, it might be as simple as adding `-a` to the `ls` command:
https://github.com/tjcsl/director4/blob/49d9f5b7e21454b741ccef416a9ddab94b4e1112/orchestrator/orchestrator/files.py#L184-L189

**Comment by ghost** [comment]
1. The code you highlighted isn't actually launching `ls`; it's running the "files helper," which has an `ls` subcommand. This doesn't take `ls`-style options; it would require changes in the files helper's code.
2. There's already an option to do this, on the "settings" tab: 
![image](https://user-images.githubusercontent.com/23221704/95103439-9a00ba00-0702-11eb-852f-82dd41b37448.png)
